spring.application.name=smart_travel
spring.datasource.url=jdbc:postgresql://dpg-d6of9kf5gffc73bkr6b0-a.oregon-postgres.render.com/tt_database_d11n
spring.datasource.username=tt_database_d11n_user
spring.datasource.password=pXrtcwiAIoYva71wdSQJYrfeIrMWCpqJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080